### ISSUE TITLE
tf-aws-vpn

### ISSUE THREAD

**Issue by ellerbrock** [terraform-aws-modules/terraform-aws-vpn-gateway#1]
hey mate,

have a look, maybe helps: https://github.com/ellerbrock/tf-aws-vpn-connection

cheers maik

**Comment by antonbabenko** [comment]
Hi Maik,

Thanks for the link! Your code creates `aws_vpn_connection`, and [the one we have already](https://github.com/terraform-community-modules/tf_aws_vpn_gw/blob/master/main.tf) creates `aws_vpn_gateway` and `aws_vpn_gateway_attachment`, but what we really need is a Terraform module which handles various setups of VPN on AWS from end-to-end.

Please let me know if you have such solution already, or saw it online.

**Comment by ellerbrock** [comment]
i wrote a few terraform modules for myself to automatically configure all the sub accounts (we run a multi account aws strategy for isolation and security. for that i create the vpc, vpn connection and so und with lots of small modules you can find here: https://github.com/ellerbrock?utf8=%E2%9C%93&tab=repositories&q=tf-aws

another good source may interesting for your needs could be:
- https://registry.terraform.io/browse?provider=aws
- https://github.com/terraform-aws-modules
- https://github.com/terraform-aws-modules/terraform-aws-vpc

cheers maik
