### ISSUE TITLE
Create branch terraform011

### ISSUE THREAD

**Issue by miguelaferreira** [terraform-aws-modules/terraform-aws-vpn-gateway#22]
Can a maintainer please create a branch `terraform011` from tag `v0.6.1`?

Users that haven't yet upgraded to terraform 0.12 would still appreciate support for 0.11.

**Comment by miguelaferreira** [comment]
I have a PR ready to make to branch `terraform011` from miguelaferreira/terraform-aws-vpn-gateway@53139c2

**Comment by antonbabenko** [comment]
Thanks Miguel for all you do (incl. opening and fixing issues!)

The branch has been just created - https://github.com/terraform-aws-modules/terraform-aws-vpn-gateway/tree/terraform011
