### ISSUE TITLE
Incorrect variable referenced in complete-vpn-gateway-with-static-routes example 

### ISSUE THREAD

**Issue by tkent** [terraform-aws-modules/terraform-aws-vpn-gateway#23]
I was reviewing the complete-vpn-gateway-with-static-routes example and noticed a minor problem.

I'm pretty sure the variable `vpc_private_subnets` should be used to define the private subnets in the vpc module, but it's used to define the public subnets instead ([see here](https://github.com/terraform-aws-modules/terraform-aws-vpn-gateway/blob/e4e0211af60fb2b2956f6df1b859ca5f2ddb3bc7/examples/complete-vpn-gateway-with-static-routes/main.tf#L50)).

**Comment by antonbabenko** [comment]
Fixed in #24, and [v2.1.0](https://github.com/terraform-aws-modules/terraform-aws-vpn-gateway/releases/v2.1.0) has been released.
