### ISSUE TITLE
Can you import an existing VPN?

### ISSUE THREAD

**Issue by runtman** [terraform-aws-modules/terraform-aws-vpn-gateway#27]
We use this module and also have manual assets, can I use this module with the older assets by importing them? I'm not sure how to map them?

**Comment by miguelaferreira** [comment]
I guess you have figured it out @runtman, but if you still struggle with importing the resources I would be happy to help you out.

**Comment by runtman** [comment]
Hey, yes I figured it out.

From memory it was something like

`terraform import module.foo.aws_vpn_connection.default {CONNECTIONID}`

**Comment by miguelaferreira** [comment]
Great 👍
