### ISSUE TITLE
Make examples to work as expected

### ISSUE THREAD

**Issue by antonbabenko** [terraform-aws-modules/terraform-aws-vpn-gateway#3]
@miguelaferreira I hope you don't mind finishing this as soon as possible.

The instructions described in [README.md](https://github.com/terraform-aws-modules/terraform-aws-vpn-gateway/blob/master/examples/complete-vpn-gateway-with-static-routes/README.md) in each example directory should work (terraform init => plan => apply => destroy). It is one of the requirements for any good module, especially in `terraform-aws-modules` :)

Now there are 2 main problems with them:
- [ ] terraform init => terraform plan => `* module.vpn_gateway.aws_vpn_gateway_route_propagation.private_subnets_vpn_routing: aws_vpn_gateway_route_propagation.private_subnets_vpn_routing: value of 'count' cannot be computed`
- [ ] `vpc_subnet_ids` var in [examples/complete-vpn-gateway-with-static-routes/main.tf]
(https://github.com/terraform-aws-modules/terraform-aws-vpn-gateway/blob/master/examples/complete-vpn-gateway-with-static-routes/main.tf#L10)

Thanks!

**Comment by miguelaferreira** [comment]
I'm going to look into it now

**Comment by miguelaferreira** [comment]
I've made a PR to address the issues you found, thanks for that.

We should setup CI. I saw that you use circleci for the VPC module.
I use it too myself and when I have some time to invest on that I'll give it a go.

**Comment by antonbabenko** [comment]
Great work (again).

Regarding CI there were several discussions already in several places. If you can add basic tflint by copying it from other modules then let's do it, and we add more sophisticated process in a couple of weeks or so (I work on the similar in a closed-source project now).
