### ISSUE TITLE
Error when using example <complete-vpn-connection-transit-gateway>

### ISSUE THREAD

**Issue by eici** [terraform-aws-modules/terraform-aws-vpn-gateway#31]
Terraform v0.12.20
provider.aws v2.47.0

if i do:
 - git clone https://github.com/terraform-aws-modules/terraform-aws-vpn-gateway.git
 - cd terraform-aws-vpn-gateway/examples/complete-vpn-connection-transit-gateway
 - terraform init
 - terraform plan

i get the error message down below.

```
terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

Error: Invalid template interpolation value

  on ../../main.tf line 13, in locals:
  13:   connection_identifier = var.connect_to_transit_gateway ? "TGW ${var.transit_gateway_id}" : "VPC ${var.vpc_id}"
    |----------------
    | var.vpc_id is null

The expression result is null. Cannot include a null value in a string
template.```

**Comment by dinodam** [comment]
I have the same issue as mentioned above. 

Terraform v0.12.24
+ provider.aws v2.54.0

I just copied your example to a local file and call the module remotely

`#create VPN gatway

module "vpn_gateway_1" {
  source  = "terraform-aws-modules/vpn-gateway/aws"
  version = "~> 2.0"

  transit_gateway_id  = aws_ec2_transit_gateway.this.id
  customer_gateway_id = module.vpc.cgw_ids[0]

  # tunnel inside cidr & preshared keys (optional)
  tunnel1_inside_cidr   = "169.254.44.88/30"
  tunnel2_inside_cidr   = "169.254.44.100/30"
  tunnel1_preshared_key = "1234567890abcdefghijklmn"
  tunnel2_preshared_key = "abcdefghijklmn1234567890"
}

module "vpn_gateway_2" {
  source  = "terraform-aws-modules/vpn-gateway/aws"
  version = "~> 2.0"

  transit_gateway_id  = aws_ec2_transit_gateway.this.id
  customer_gateway_id = module.vpc.cgw_ids[1]

  # tunnel inside cidr & preshared keys (optional)
  tunnel1_inside_cidr   = "169.254.33.88/30"
  tunnel2_inside_cidr   = "169.254.33.100/30"
  tunnel1_preshared_key = "1234567890abcdefghijklmn"
  tunnel2_preshared_key = "abcdefghijklmn1234567890"
}

resource "aws_ec2_transit_gateway" "this" {
  description = "complete-vpn-connection-transit-gateway"
}

resource "aws_ec2_transit_gateway_vpc_attachment" "this" {
  subnet_ids         = module.vpc.private_subnets
  transit_gateway_id = aws_ec2_transit_gateway.this.id
  vpc_id             = module.vpc.vpc_id
}`
