### ISSUE TITLE
Feature request - Tunnel details

### ISSUE THREAD

**Issue by iqre8** [terraform-aws-modules/terraform-aws-vpn-gateway#43]
Thanks for all the hard work.
It seems you can modify the tunnel details in the AWS gui.
Things like phase 1 and phase 2 encryption settings etc.
See https://docs.aws.amazon.com/vpn/latest/s2svpn/VPNTunnels.html

**Comment by angelabad** [comment]
I need these features too, aws provider has them now, and apply with latest version of this module fails
Thanks!

**Comment by antonbabenko** [comment]
@Art3mK has made it and [v2.6.0](https://github.com/terraform-aws-modules/terraform-aws-vpn-gateway/releases/v2.6.0) has been just released.

**Comment by angelabad** [comment]
Thanks @antonbabenko for the fix!
