### ISSUE TITLE
Feature Request - Add inputs to configure local_ipv4_network_cidr and remote_ipv4_network_cidr

### ISSUE THREAD

**Issue by cmlccie** [terraform-aws-modules/terraform-aws-vpn-gateway#44]
Some statically-routed policy-based VPNs, like _Cisco Meraki_, require you to configure the [local_ipv4_network_cidr](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/vpn_connection#local_ipv4_network_cidr) and [remote_ipv4_network_cidr](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/vpn_connection#remote_ipv4_network_cidr) VPN connection parameters. **These parameters cannot be configured using the current terraform-aws-vpn-gateway module** and they are required to create a functional policy-based VPN in scenarios when you are not tunneling all traffic to AWS.

> **_Note:_** There is presently an issue https://github.com/hashicorp/terraform-provider-aws/issues/16879 with the aws provider that prevents you from configuring any CIDR prefix with less than 32 network bits. The issue will need to be resolved before this feature can be added to this module.

**Comment by antonbabenko** [comment]
Fixed in #58 

[v2.11.0](https://github.com/terraform-aws-modules/terraform-aws-vpn-gateway/releases/v2.11.0) has been just released.
