### ISSUE TITLE
Q: Workaround for computed resource output as shared key?

### ISSUE THREAD

**Issue by naseemkullah** [terraform-aws-modules/terraform-aws-vpn-gateway#65]
it cannot use a computed resource output (e.g. random_password.my_shared_key.result) as input for the shared key

Is this an anti-pattern or should the module be able to support that?

**Comment by naseemkullah** [comment]
It probably makes sense to always store any computed resource ouput password as a secret outside of terraform and then use a data source.

**Comment by antonbabenko** [comment]
There is a long-standing issue in Terraform - https://github.com/hashicorp/terraform/issues/4149 - which means that users need to create such resources in advance using `-target` and then run `terraform apply` to create the rest of resources.
