### ISSUE TITLE
Remove hard requirement for Customer Gateway

### ISSUE THREAD

**Issue by webmin88** [terraform-aws-modules/terraform-aws-vpn-gateway#7]
I'm requesting a review of the required argument: customer_gateway_id.

Description:
I have use cases where I would be working with a virtual gateway (vpn gateway) but not setting up a VPN connection or would require a customer_gateway_id, i.e., working with direct connect virtual interfaces.

Expected Behavior:
If the create_vpn_connection argument is set to false, it should remove the required argument customer_gateway_id

Please reach out if additional feedback is required.

**Comment by antonbabenko** [comment]
Hi! I am not sure I understand this entirely.

First, `aws_vpn_connection` requires `customer_gateway_id` to be set.

Second, if `create_vpn_connection = false` then [aws_vpn_connection](https://www.terraform.io/docs/providers/aws/r/vpn_connection.html) resource is not created.

**Comment by veilig2000** [comment]
I think what is being asked is: the aws_vpn_connection is not created when you set `create_vpn_connection = false`, but the variable for the customer_gateway_id is still required.

```
###############
# VPN 1 Gateway
###############
module "vpn1_gateway" {
  source = "terraform-aws-modules/vpn-gateway/aws"
  version = "1.5.0"

  vpn_gateway_id      = "${module.vpc.vgw_id}"
  customer_gateway_id = "${aws_customer_gateway.main.id}" # <--- still needed, even if vpn connection is not created
  vpc_id              = "${module.vpc.vpc_id}"

  create_vpn_connection         = "${var.enable_vpn_gateway}"
  create_vpn_gateway_attachment = "${var.enable_vpn_gateway}"

  ...
}

#########################
# Main Gateway
#########################
resource "aws_customer_gateway" "main" {
  count = "${var.enable_vpn_gateway ? 1 : 0}"

  bgp_asn    = 65000
  ip_address = "${var.main_gateway_ip_address}"
  type       = "ipsec.1"
}
```

In my scenario, I need a VPN for my production VPC, but I don't need one for the VPC in my staging account.  so a setup like I have above creates an error

```
* module.vpn1_gateway.var.customer_gateway_id: Resource 'aws_customer_gateway.main' not found for variable 'aws_customer_gateway.main.id'
```

**Comment by miguelaferreira** [comment]
I don’t see a problem in giving customer_gateway_id a default value (ie “”).

If then the module is espected to create a VPN connection but has no valid customer gateway id, an error will be spat out.

**Comment by miguelaferreira** [comment]
Is this something that can be closed @antonbabenko @brandoconnor ?

**Comment by webmin88** [comment]
Hey there,

Sorry, I've been away from working with Terraform for a while. I don't see any commit referencing this issue, and it seems there's still some confusion around what this would accomplish?

As best as I can explain it, I had a scenario where I need to build and attach a virtual gateway and set some routes; I believe it had to do with Direct Connect. The only component I did not need was the customer gateway which is why I asked for a way to remove the hard requirement on the customer_gateway_id if create_vpn_connection = false.

Hope that helps.

**Comment by miguelaferreira** [comment]
Hi @webmin88.

I think I understand what you are asking, but I don't know of a way to achieve it. AFAIK it is not possible to make `customer_gateway_id` optional depending on the value of `create_vpn_connection`. Therefore, I suggest that when setting `create_vpn_connection = false` also set `customer_gateway_id = ""`.
