### ISSUE TITLE
Output refers to sensitive values

### ISSUE THREAD

**Issue by avysotsk** [terraform-aws-modules/terraform-aws-vpn-gateway#80]
Version of module 3.0.1
❯ terraform --version
Terraform v1.3.4
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v4.39.0

Error message after apply 

│ Error: Output refers to sensitive values
│
│   on outputs.tf line 81:
│   81: output "vpn_connection_customer_gateway_configuration" {
│
│ To reduce the risk of accidentally exporting sensitive data that was
│ intended to be only internal, Terraform requires that any root module
│ output containing sensitive data be explicitly marked as sensitive, to
│ confirm your intent.
│
│ If you do intend to export this data, annotate the output value as
│ sensitive by adding the following argument:
│     sensitive = true

**Comment by amontalban** [comment]
I'm having the exact same issue.

**Comment by amontalban** [comment]
@antonbabenko looks like this has been addressed in multiple PRs but none of them were merged:

- #54 
- #71 
- #64

Any chance you can help us by adding that line to the output so we don't have to use a fork for this?

Thanks!

**Comment by stefan-matic** [comment]
Experiencing same issue. Setting the `vpn_connection_customer_gateway_configuration` output with `sensitive = true` resolves the problem.

**Comment by stefan-matic** [comment]
@antonbabenko Do we have anyone that can verify these changes and accept a PR for it?

**Comment by davidferguson-cr** [comment]
Also seeing this so let's keep it open.  I believe we should also be marking the pre-shared key outputs below as `sensitive = true`?

- `tunnel1_preshared_key`
- `tunnel2_preshared_key`

**Comment by stefan-matic** [comment]
@davidferguson-cr Yeah, I believe so. I could add one more commit but waiting for some response from maintainers if we want to implement it this way.

**Comment by antonbabenko** [comment]
This issue has been resolved in version 3.2.0 :tada:

**Comment by antonbabenko** [comment]
Thank you all for following up on this one!

**Comment by davidferguson-cr** [comment]
@antonbabenko Thanks!  But what about the PSK outputs?  Should I open a new issue/PR?

**Comment by antonbabenko** [comment]
@davidferguson-cr Yes, please open a PR for two PSKs.
