### ISSUE TITLE
Add variable for Name tag

### ISSUE THREAD

**Issue by nicon89** [terraform-aws-modules/terraform-aws-vpn-gateway#81]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - Yes ✅: please list the AWS provider version which introduced this functionality

## Describe the solution you'd like.
I have multiple VPN connections and name "VPN Connection between VPC vpc-zyx and Customer Gateway cgw-xyz" doesn't tell much. 
Do you think you can variablize it with default option set as it is right now?

**Comment by gartemiev** [comment]
@bryantbiggs @antonbabenko @dynamike ,

is this something which you can do? There was already another request for this opened in the end of 2021 but it was ignored and closed automatically: https://github.com/terraform-aws-modules/terraform-aws-vpn-gateway/issues/61
