### ISSUE TITLE
Feature request - Outside IP address type & Transport transit gateway attachment ID

### ISSUE THREAD

**Issue by avivmazon** [terraform-aws-modules/terraform-aws-vpn-gateway#93]
Thanks for the hard work.

When working with direct connect and wanting to create a private IP VPN, you need to configure the "Outside IP address type" to "PrivateIpv4" and choose the Direct Connect Transit Gateway attachment.

Can you please add this feature?

**Comment by cdsre** [comment]
This seems like it should be an easy feature to implement. Terraform support these to attributes

```
outside_ip_address_type - (Optional, Default PublicIpv4) Indicates if a Public S2S VPN or Private S2S VPN over AWS Direct Connect. Valid values are PublicIpv4 | PrivateIpv4
```

```
transport_transit_gateway_attachment_id - (Required when outside_ip_address_type is set to PrivateIpv4). The attachment ID of the Transit Gateway attachment to Direct Connect Gateway. The ID is obtained through a data source only.
```

We should be able to just set these vars in the module with a default of `null` which means we can define it in the resource but wont pass it unless the called explicitly sets it. I have another pull request which was a large refactor to this module. If that gets approved and merged I will then pick up this feature request. I dont have the resources to setup and test this with direct connect so I would do regression tests on the examples and then you would need to test it yourself.

**Comment by avivmazon** [comment]
Great! 
Let me know when it's merged and i will test it on my environment.
Thanks.

**Comment by avivmazon** [comment]
.

**Comment by avivmazon** [comment]
.
