### ISSUE TITLE
Enable acceleration flag when use TGW

### ISSUE THREAD

**Issue by rustjalm** [terraform-aws-modules/terraform-aws-vpn-gateway#98]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? 

  - Yes ✅: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/vpn_connection#enable_acceleration

## Is your request related to a problem? Please describe.
To use Global Accelerator for low latency and high throughput, you can enable acceleration on site-to-site VPN connections.

## Describe the solution you'd like.
An option enable_acceleration would be great that, maybe in combination with a check if connect_to_transit_gateway is set as this is only usable with tgw.

## Describe alternatives you've considered.
Can't see any.

## Additional context

I have seen same issues and feat requests for adding this flag. Why is the requests was ingnored? It's very useful flag

**Comment by antonbabenko** [comment]
This issue has been resolved in version 4.0.0 :tada:
